server {
    listen 80;
    listen [::]:80;
    server_name wisexpert.com.ua www.wisexpert.com.ua;

    return 301 https://wisexpert.com.ua$request_uri;
}

# Redirect www HTTPS → non-www HTTPS
server {
    listen 443 ssl;
    server_name www.wisexpert.com.ua;

    ssl_certificate /etc/letsencrypt/live/wisexpert.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wisexpert.com.ua/privkey.pem;

    return 301 https://wisexpert.com.ua$request_uri;
}

server {
    listen 443 ssl;
    server_name wisexpert.com.ua;

    ssl_certificate /etc/letsencrypt/live/wisexpert.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wisexpert.com.ua/privkey.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
